--1
SELECT EMP.EMPNAME,
  SALARY.*
FROM SALARY
JOIN EMP
ON SALARY.EMPNO = EMP.EMPNO
WHERE SALVALUE  =
  (SELECT MIN(SALVALUE) MIN_SAL FROM SALARY);

--2
SELECT E.EMPNAME
    FROM EMP E NATURAL JOIN CAREER C
    WHERE C.DEPTNO IN (
    SELECT C.DEPTNO
        FROM CAREER C NATURAL JOIN EMP E
        WHERE E.EMPNAME='RICHARD MARTIN');

--3
SELECT E.EMPNAME
    FROM EMP E NATURAL JOIN CAREER C
    WHERE (C.DEPTNO, C.JOBNO) IN (
    SELECT C.DEPTNO, C.JOBNO
        FROM CAREER C NATURAL JOIN EMP E
        WHERE E.EMPNAME='RICHARD MARTIN');

--4
SELECT EMPNO
    FROM SALARY
    WHERE (
    SELECT AVG(SALVALUE)
        FROM SALARY
        WHERE YEAR = 2000) < ANY(SALVALUE)
    OR (
    SELECT AVG(SALVALUE)
        FROM SALARY
        WHERE YEAR = 2001) < ANY(SALVALUE);

--5
SELECT EMPNO
    FROM SALARY
    WHERE (
    SELECT AVG(SALVALUE)
        FROM SALARY) < ANY(SALVALUE);

--6
SELECT YEAR
    FROM SALARY
    GROUP BY YEAR
    HAVING AVG(SALVALUE) > (
    SELECT AVG(SALVALUE)
        FROM SALARY);

--7
SELECT DISTINCT DEPTNO
FROM CAREER
WHERE (SELECT COUNT(*)
  FROM SALARY
  WHERE SALARY.EMPNO = CAREER.EMPNO
  AND SALVALUE      IS NULL) = 0
AND DEPTNO          IS NOT NULL;

--8
SELECT DEPTNO
    FROM DEPT D
    WHERE EXISTS (
    SELECT SALVALUE
        FROM CAREER C NATURAL JOIN EMP E NATURAL JOIN SALARY S
        WHERE D.DEPTNO = C.DEPTNO)
    ORDER BY DEPTNO;

--9
SELECT DEPTNO
    FROM DEPT D
    WHERE NOT EXISTS (
    SELECT SALVALUE
        FROM CAREER C NATURAL JOIN EMP E NATURAL JOIN SALARY S
        WHERE D.DEPTNO = C.DEPTNO)
    ORDER BY DEPTNO;

--10
SELECT E.EMPNAME, D.DEPTNAME, D.DEPTADDR
    FROM EMP E NATURAL JOIN CAREER C NATURAL JOIN DEPT D
    ORDER BY E.EMPNAME, C.STARTDATE;

--11
SELECT YEAR, CAST(AVG(SALVALUE) AS NUMBER(10)) AS INTSALVALUE
    FROM SALARY
    GROUP BY YEAR
    ORDER BY YEAR;

--12
SELECT EMPNO, EMPNAME,
    CASE
        WHEN MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 >= 20 AND MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 <= 30
            THEN 'A'
        WHEN MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 >= 31 AND MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 <= 40
            THEN 'B'
        WHEN MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 >= 41 AND MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 <= 50
            THEN 'C'
        WHEN MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 >= 51 AND MONTHS_BETWEEN (SYSDATE, BIRTHDATE) / 12 <= 60
            THEN 'D'
        ELSE NULL
    END
    AS AGE_GROUP
    FROM EMP;

--13
SELECT D.DEPTNO,
    CASE
        WHEN D.DEPTNO <= 20 THEN CONCAT('BI', CAST (D.DEPTNO AS VARCHAR(10)))
        WHEN D.DEPTNO >= 30 THEN CONCAT('LN', CAST (D.DEPTNO AS VARCHAR(10)))
    END
    AS NEWDEPTNO, D.DEPTNAME, D.DEPTADDR
    FROM DEPT D

--14
SELECT EMPNO, EMPNAME,
    COALESCE(BIRTHDATE, to_date('01-01-1000', 'dd-mm-yyyy')) AS BIRTHDATE
    FROM EMP
