SELECT E.EMPNAME || ' works for ' || M.EMPNAME AS Emp_Manager 
FROM EMP E 
INNER JOIN EMP M 
ON E.MANAGER_ID = M.EMPNO; 

SELECT EMPNAME || ' reports to ' || PRIOR EMPNAME AS "Walk Top Down" 
FROM EMP 
START WITH MANAGER_ID IS NULL 
CONNECT BY PRIOR EMPNO = MANAGER_ID; 

SELECT LTRIM(SYS_CONNECT_BY_PATH (EMPNAME, '->'), '->') AS LEAF__BRANCH__ROOT 
FROM EMP 
WHERE MANAGER_ID IS NULL 
START WITH EMPNAME = 'CLARK' 
CONNECT BY PRIOR MANAGER_ID = EMPNO; 

SELECT LTRIM(SYS_CONNECT_BY_PATH (EMPNAME, '->'), '->') AS EMP_Tree 
FROM EMP 
START WITH MANAGER_ID IS NULL 
CONNECT BY PRIOR EMPNO = MANAGER_ID; 

SELECT LPAD(' ', LEVEL, '*') || EMPNAME AS Org_Chart 
FROM EMP 
START WITH MANAGER_ID IS NULL 
CONNECT BY PRIOR EMPNO = MANAGER_ID; 

SELECT EMPNAME 
FROM EMP 
START WITH EMPNAME = 'ALLEN' 
CONNECT BY PRIOR EMPNO = MANAGER_ID;
